install:
 - sudo apt-get update
 - sudo apt-get install haskell-platform autoconf libtool make ncurses-dev g++ dblatex docbook-xsl docbook-utils
 - cabal update
 - cabal install happy alex
script:
 - PATH=~/.cabal/bin:$PATH ./validate.sh
